service: auth-service

provider:
    name: aws
    runtime: nodejs12.x
    region: us-east-2
    environment:
        AUTH0_CLIENT_ID: ${file(./secrets.json):AUTH0_CLIENT_ID}
        AUTH0_CLIENT_PUBLIC_KEY: ${file(./public_key)}

functions:
    auth:
        handler: handler.auth
    publicEndpoint:
        handler: handler.publicEndpoint
        events:
            - http:
                  path: api/public
                  method: post
                  cors: true
    privateEndpoint:
        handler: handler.privateEndpoint
        events:
            - http:
                  path: api/private
                  method: post
                  # See custom authorizer docs here: http://bit.ly/2gXw9pO
                  authorizer: auth
                  cors: true

resources:
    Resources:
        # This response is needed for custom authorizer failures cors support ¯\_(ツ)_/¯
        GatewayResponse:
            Type: 'AWS::ApiGateway::GatewayResponse'
            Properties:
                ResponseParameters:
                    gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
                    gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
                ResponseType: EXPIRED_TOKEN
                RestApiId:
                    Ref: 'ApiGatewayRestApi'
                StatusCode: '401'
        AuthFailureGatewayResponse:
            Type: 'AWS::ApiGateway::GatewayResponse'
            Properties:
                ResponseParameters:
                    gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
                    gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
                ResponseType: UNAUTHORIZED
                RestApiId:
                    Ref: 'ApiGatewayRestApi'
                StatusCode: '401'
        GatewayResponseDefault4XX:
            Type: 'AWS::ApiGateway::GatewayResponse'
            Properties:
                ResponseParameters:
                    gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
                    gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
                    gatewayresponse.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
                ResponseType: DEFAULT_4XX
                RestApiId:
                    Ref: 'ApiGatewayRestApi'
        GatewayResponseDefault5xx:
            Type: 'AWS::ApiGateway::GatewayResponse'
            Properties:
                ResponseParameters:
                    gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
                    gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
                    gatewayresponse.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
                ResponseType: DEFAULT_5XX
                RestApiId:
                    Ref: 'ApiGatewayRestApi'
